
tasks:
  - name: start virtual x-server
    command: |
      sh virtualfb.sh
      echo export DISPLAY=$(cat virtualfb.DISPLAY) >> ~/.bashrc
      exit

image:
  file: ./Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9000
    onOpen: ignore
    visibility: private
  - port: 9001
    onOpen: ignore
    visibility: private
  - port: 9002
    onOpen: ignore
    visibility: private



github:
  prebuilds:
    master: true
    branches: true
vscode:
  extensions:
    - ms-toolsai.jupyter
    - vscode.ipynb
    - ms-python.python
