# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: start virtual x-server
    command: sh virtuafb.sh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9000
    onOpen: ignore  
  - port: 9001
    onOpen: ignore
  - port: 9002
    onOpen: ignore
  


github:
  prebuilds:
    master: true
    branches: true