image:
  file: ./.devcontainer/Dockerfile

ports:
  - port: 9000-9050
    onOpen: ignore
    visibility: private

github:
  prebuilds:
    master: true
    branches: true

vscode:
  extensions:
    - Antyos.openscad
