{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "from viewscad import Renderer\n",
        "\n",
        "r = Renderer()\n",
        "r.width = 700\n",
        "r.height = 700\n",
        "\n",
        "render = r.render\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "from utils import ring, connection, pipe, cutout, two_sided_connection\n",
        "from solid import cylinder, translate, rotate, cube\n",
        "from solid.utils import *\n",
        "from viewscad import Renderer\n",
        "\n",
        "r = Renderer()\n",
        "r.width = 700\n",
        "r.height = 700\n",
        "\n",
        "render = r.render\n",
        "\n",
        "\n",
        "def bottom_grid(d=60, w=2, hole_size=6, hole_gap=2):\n",
        "    plate = cylinder(h=w, d=d, segments=100)\n",
        "    hole = cylinder(h=w, d=hole_size, segments=10)\n",
        "    pane = range(-d//2, d//2, hole_size+hole_gap)\n",
        "    transition = ring(d1=d, h=w, w=w*2)\n",
        "\n",
        "    holes = [translate((x, y, 0))(hole) for x in pane for y in pane]\n",
        "\n",
        "    return plate - holes + transition\n",
        "\n",
        "\n",
        "def spin_around_tower(obj, count=4, alpha=45, h=160):\n",
        "    angles = range(180, 540, int(360/count))\n",
        "    # drehen und dann kippen\n",
        "    return translate((0, 0, h/2))([rotate((alpha, 0, z))(obj) for z in angles])\n",
        "\n",
        "\n",
        "def cup_con(d1=52, d2=60, w=2, height=80, inlet_delta=5):\n",
        "    c = d2\n",
        "    gradient = (d2-d1)/height\n",
        "    inlet = (gradient*inlet_delta+w) * 2\n",
        "    socket_d1_delta = d1 + inlet\n",
        "    socket_d2_delta = d2 + inlet\n",
        "    c = cutout(c)\n",
        "\n",
        "    base = ring(d1=socket_d1_delta, d2=socket_d2_delta, h=height, w=w)\n",
        "    socket = base - c\n",
        "\n",
        "    cup = ring(d1=d1, d2=d2, w=w, h=height)\n",
        "    cup += bottom_grid(d=d1, w=w)\n",
        "\n",
        "    outline = cylinder(d1=d1, d2=d2, h=height, segments=100)\n",
        "\n",
        "    return (socket, cup, outline)\n",
        "\n",
        "\n",
        "def aero_tank(d=180, height=180, wall=2, socket_h=20, tooth=4):\n",
        "    body = ring(d1=d, h=height, w=wall)\n",
        "    bottom = cylinder(d=d, h=wall, segments=100)\n",
        "    (_, socket) = connection(d=d, h=socket_h,\n",
        "                             wall=wall, tooth_depth=tooth, tooth_height=tooth*2)\n",
        "\n",
        "    return bottom + body + up(height-socket_h)(socket)\n",
        "\n",
        "\n",
        "def aero_tower(w=1, h=160, d=160, socket_h=20, pipe_count=1, alpha=45, cup_d=60, cup_h=80, tooth=4):\n",
        "    aero_tower = pipe(d=d, h=h, w=w, tooth=tooth, socket_h=socket_h)\n",
        "    (cup_s, cup, cup_outline) = cup_con(d1=cup_d-cup_h //\n",
        "                                        10, d2=cup_d, w=w, height=cup_h, inlet_delta=5)\n",
        "    outline = cylinder(d=d, h=d, segments=100)\n",
        "    holes = spin_around_tower(translate((0, 0, h/2-4))\n",
        "                              (cup_outline), count=pipe_count, alpha=alpha)\n",
        "    sockets = spin_around_tower(\n",
        "        translate((0, 0, h/2+w*5))(cup_s), h=d, count=pipe_count, alpha=alpha)\n",
        "\n",
        "    holes = translate((0, 0, -h/2))(holes)\n",
        "    sockets = translate((0, 0, -h/2))(sockets)\n",
        "    aero_tower = aero_tower - holes + sockets\n",
        "    aero_tower *= outline\n",
        "\n",
        "    tank = aero_tank(d=180, height=180, wall=2, tooth=tooth)\n",
        "    adapter = two_sided_connection(outer_d=180, outer_w=2, outer_tooth=tooth,\n",
        "                                   height=socket_h, inner_d=d, inner_w=w, inner_tooth=tooth)\\\n",
        "        + cylinder(r=90-2-tooth-0.2, h=w, segments=100)\\\n",
        "        - cylinder(d=6, h=w)\n",
        "\n",
        "    return (aero_tower, cup, tank, adapter)\n",
        "\n",
        "\n",
        "(tower, cup, tank, adapter) = aero_tower(pipe_count=5)\n",
        "render(tower, outfile='./outfiles/aero_tower.stl')\n",
        "render(cup, outfile='./outfiles/plant_cup.stl')\n",
        "render(tank, outfile='./outfiles/aero_tower_tank.stl')\n",
        "render(adapter, outfile='./outfiles/aero_tower_tank_adapter.stl')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "\n",
        "from utils import pipe, ring, connection, mount_to_bottom, tended_obj, cutout, sliding_connector\n",
        "from solid import cylinder, translate, rotate, cube, hull\n",
        "from solid.utils import *\n",
        "from viewscad import Renderer\n",
        "from math import sqrt\n",
        "\n",
        "r = Renderer()\n",
        "r.width = 700\n",
        "r.height = 700\n",
        "\n",
        "render = r.render\n",
        "\n",
        "\n",
        "def tower_head(d=160, w=2, tooth=4, socket_h=20, h=100, gap=0.1):\n",
        "    delta_r = w + tooth + gap\n",
        "    base_d = d-delta_r*2\n",
        "    filter_d = 8\n",
        "    filter_l = 100\n",
        "    piezo_d = 20\n",
        "    piezo_h = 3\n",
        "    slider_l = 30\n",
        "    slider_w = 20\n",
        "    pump_d = 27.4\n",
        "    pump_hole_delta = -((pump_d + slider_l)/2 + w*2)\n",
        "\n",
        "    # head body\n",
        "    body = pipe(d=d, w=w, tooth=tooth, socket_h=socket_h, h=h)\n",
        "\n",
        "    base = cylinder(d=base_d, h=w, segments=100)\n",
        "    (slider_s, slider_a) = sliding_connector(\n",
        "        length=slider_l, width=slider_w, gap=0.05)\n",
        "\n",
        "    cable_hole = rotate(90)(\n",
        "        translate((-d/2, 0, h/2))(\n",
        "            rotate((0, 90, 0))(\n",
        "                cylinder(d=4, h=2*w, segments=100)\n",
        "            )\n",
        "        )\n",
        "    )\n",
        "\n",
        "    pump_hole = translate((pump_hole_delta, 0, 0))(\n",
        "            cylinder(d=pump_d, h=20, segments=100))\n",
        "    \n",
        "\n",
        "    head = body + base - cable_hole\n",
        "    head -= translate((-slider_l/2, 0, 0))(pump_hole + slider_s)\n",
        "\n",
        "    # fogger module\n",
        "\n",
        "    fogger = down(piezo_h/2)(\n",
        "        cube((slider_l, piezo_d+4, piezo_d+piezo_h+4), center=True)\n",
        "        + translate((-slider_l/2, 0, (piezo_d+piezo_h+4)/2))(slider_a)\n",
        "    )\n",
        "\n",
        "    fogger += right((slider_l+piezo_h)/2)(rotate((0, 90, 0))(\n",
        "        hull()(\n",
        "            cylinder(d=piezo_d+4, h=piezo_h+2, center=True, segments=100),\n",
        "            translate((piezo_h, 0, -(piezo_h)/2))(\n",
        "                cylinder(d=piezo_d+4, h=.1, center=True, segments=100))\n",
        "        )\n",
        "        - cylinder(d=piezo_d, h=piezo_h, center=True, segments=100)\n",
        "        - cylinder(d=piezo_d-4, h=piezo_h+2, center=True, segments=100)\n",
        "        - translate((-2*piezo_d, -piezo_d, -piezo_h)\n",
        "                    )(cube((piezo_d*2, piezo_d*2, piezo_h*2)))\n",
        "    ))\n",
        "\n",
        "    fogger -= down(4)(rotate((0, 80, 0))(\n",
        "        cylinder(d=filter_d, h=filter_l, center=True, segments=100)\n",
        "    ))\n",
        "\n",
        "    transition_delta = 4\n",
        "    tank_width_addon = 10\n",
        "    fogger += translate((-(slider_l+pump_d/2+tank_width_addon)/2, 0, -piezo_h))(\n",
        "        cube((pump_d/2+tank_width_addon, piezo_d+transition_delta, piezo_d+transition_delta), center=True)\n",
        "        - translate((1, 0, 2))(\n",
        "            cube((pump_d/2-2+tank_width_addon, piezo_d, piezo_d+2), center=True)\n",
        "        )\n",
        "        - translate((0, 0, piezo_d*0.75))(\n",
        "            cube((pump_d/2+tank_width_addon, piezo_d+transition_delta, piezo_d+2), center=True)\n",
        "        )\n",
        "    )\n",
        "\n",
        "    cable_s = 2\n",
        "    cable_rail = cube((slider_l/2+cable_s, cable_s, slider_w))\n",
        "    fogger -= translate((-cable_s, -1, piezo_d/2))(cable_rail)\n",
        "\n",
        "    # head lid\n",
        "\n",
        "    head_lid_adapter_inner_d = d-(w+gap+tooth)*2\n",
        "    head_lid_body = cylinder(d=head_lid_adapter_inner_d, segments=100, h=w)\n",
        "    handle_base_thickness = 10\n",
        "    handle_top_thickness = handle_base_thickness + (socket_h-w)*2\n",
        "\n",
        "    (head_lid_adapter, _) = connection(d=d, h=socket_h,\n",
        "                                       wall=w, tooth_depth=tooth, tooth_height=2*tooth, gap=0.2)\n",
        "\n",
        "    head_lid_body += hull()(\n",
        "        up(w/2)(cube((handle_base_thickness, head_lid_adapter_inner_d, w), center=True)),\n",
        "        up((socket_h-w/2))(cube((handle_top_thickness,\n",
        "                                 head_lid_adapter_inner_d, w), center=True)),\n",
        "    ) * cylinder(d=head_lid_adapter_inner_d, segments=100, h=socket_h)\n",
        "\n",
        "    head_lid = head_lid_adapter + head_lid_body\n",
        "\n",
        "    return (head, fogger, head_lid)\n",
        "\n",
        "\n",
        "(head, fogger, head_lid) = tower_head()\n",
        "\n",
        "render(head, outfile='outfiles/aero_tower_head.stl')\n",
        "render(fogger, outfile='outfiles/aero_tower_head_fogger.stl')\n",
        "render(head_lid, outfile='outfiles/aero_tower_head_lid.stl')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {},
      "outputs": [
        {
          "ename": "KeyboardInterrupt",
          "evalue": "",
          "output_type": "error",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
            "Cell \u001b[0;32mIn [1], line 47\u001b[0m\n\u001b[1;32m     42\u001b[0m     pipe \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m up(socket_h \u001b[38;5;241m+\u001b[39m transition_h)(socket)\n\u001b[1;32m     44\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m pipe\n\u001b[0;32m---> 47\u001b[0m \u001b[43mrender\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtower_module_thread_adapter\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43moutfile\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m./outfiles/tower_module_size_transition.stl\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
            "File \u001b[0;32m~/.local/lib/python3.9/site-packages/viewscad/renderer.py:384\u001b[0m, in \u001b[0;36mRenderer.render\u001b[0;34m(self, in_obj, **kw)\u001b[0m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=381'>382</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(in_obj, solid\u001b[39m.\u001b[39mOpenSCADObject):\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=382'>383</a>\u001b[0m     kw[\u001b[39m'\u001b[39m\u001b[39mscad_object\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m in_obj\n\u001b[0;32m--> <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=383'>384</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcreate_rendered_obj_if_needed(in_obj, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkw)\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=384'>385</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mhasattr\u001b[39m(in_obj, \u001b[39m'\u001b[39m\u001b[39mrendered_object\u001b[39m\u001b[39m'\u001b[39m):\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=385'>386</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_render_obj(in_obj\u001b[39m.\u001b[39mrendered_object, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkw)\n",
            "File \u001b[0;32m~/.local/lib/python3.9/site-packages/viewscad/renderer.py:582\u001b[0m, in \u001b[0;36mRenderer.create_rendered_obj_if_needed\u001b[0;34m(self, openSCADObj, **kw)\u001b[0m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=579'>580</a>\u001b[0m \u001b[39mif\u001b[39;00m scad_str \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=580'>581</a>\u001b[0m     scad_str \u001b[39m=\u001b[39m solid\u001b[39m.\u001b[39mscad_render(openSCADObj)\n\u001b[0;32m--> <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=581'>582</a>\u001b[0m rend_obj \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mrender_openscad_str(scad_str, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkw)\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=582'>583</a>\u001b[0m \u001b[39mif\u001b[39;00m rend_obj \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=583'>584</a>\u001b[0m     openSCADObj\u001b[39m.\u001b[39mrendered_object \u001b[39m=\u001b[39m rend_obj\n",
            "File \u001b[0;32m~/.local/lib/python3.9/site-packages/viewscad/renderer.py:608\u001b[0m, in \u001b[0;36mRenderer.render_openscad_str\u001b[0;34m(self, openscad_str, **kw)\u001b[0m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=605'>606</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=606'>607</a>\u001b[0m     kw[\u001b[39m'\u001b[39m\u001b[39mrough\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m            \n\u001b[0;32m--> <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=607'>608</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mrender_to_file(openscad_str, openscad_out_file, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkw)\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=608'>609</a>\u001b[0m     \u001b[39mif\u001b[39;00m openscad_out_file\u001b[39m.\u001b[39mfind(\u001b[39m'\u001b[39m\u001b[39m.stl\u001b[39m\u001b[39m'\u001b[39m) \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m \u001b[39m0\u001b[39m:                \n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=609'>610</a>\u001b[0m         \u001b[39m#self._render_stl(openscad_out_file)\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=610'>611</a>\u001b[0m         return_obj \u001b[39m=\u001b[39m RenderedObject(\u001b[39mopen\u001b[39m(openscad_out_file))\n",
            "File \u001b[0;32m~/.local/lib/python3.9/site-packages/viewscad/renderer.py:365\u001b[0m, in \u001b[0;36mRenderer.render_to_file\u001b[0;34m(self, openscad_str, fl_name, **kw)\u001b[0m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=362'>363</a>\u001b[0m \u001b[39m# now run openscad to generate stl:\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=363'>364</a>\u001b[0m cmd \u001b[39m=\u001b[39m [\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mopenscad_exec, \u001b[39m'\u001b[39m\u001b[39m-o\u001b[39m\u001b[39m'\u001b[39m, fl_name, scad_tmp_file]\n\u001b[0;32m--> <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=364'>365</a>\u001b[0m out \u001b[39m=\u001b[39m subprocess\u001b[39m.\u001b[39;49mcheck_output(cmd)\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=365'>366</a>\u001b[0m \u001b[39mif\u001b[39;00m out \u001b[39m!=\u001b[39m \u001b[39mb\u001b[39m\u001b[39m'\u001b[39m\u001b[39m'\u001b[39m: \u001b[39mprint\u001b[39m(out)\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=366'>367</a>\u001b[0m \u001b[39m#if return_code < 0:\u001b[39;00m\n\u001b[1;32m    <a href='file:///home/malte/.local/lib/python3.9/site-packages/viewscad/renderer.py?line=367'>368</a>\u001b[0m \u001b[39m#    raise Exception('openscad command line returned code {}'.format(return_code))\u001b[39;00m\n",
            "File \u001b[0;32m/usr/lib/python3.9/subprocess.py:424\u001b[0m, in \u001b[0;36mcheck_output\u001b[0;34m(timeout, *popenargs, **kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=420'>421</a>\u001b[0m         empty \u001b[39m=\u001b[39m \u001b[39mb\u001b[39m\u001b[39m'\u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=421'>422</a>\u001b[0m     kwargs[\u001b[39m'\u001b[39m\u001b[39minput\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m empty\n\u001b[0;32m--> <a href='file:///usr/lib/python3.9/subprocess.py?line=423'>424</a>\u001b[0m \u001b[39mreturn\u001b[39;00m run(\u001b[39m*\u001b[39;49mpopenargs, stdout\u001b[39m=\u001b[39;49mPIPE, timeout\u001b[39m=\u001b[39;49mtimeout, check\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=424'>425</a>\u001b[0m            \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\u001b[39m.\u001b[39mstdout\n",
            "File \u001b[0;32m/usr/lib/python3.9/subprocess.py:507\u001b[0m, in \u001b[0;36mrun\u001b[0;34m(input, capture_output, timeout, check, *popenargs, **kwargs)\u001b[0m\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=504'>505</a>\u001b[0m \u001b[39mwith\u001b[39;00m Popen(\u001b[39m*\u001b[39mpopenargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs) \u001b[39mas\u001b[39;00m process:\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=505'>506</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> <a href='file:///usr/lib/python3.9/subprocess.py?line=506'>507</a>\u001b[0m         stdout, stderr \u001b[39m=\u001b[39m process\u001b[39m.\u001b[39;49mcommunicate(\u001b[39minput\u001b[39;49m, timeout\u001b[39m=\u001b[39;49mtimeout)\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=507'>508</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m TimeoutExpired \u001b[39mas\u001b[39;00m exc:\n\u001b[1;32m    <a href='file:///usr/lib/python3.9/subprocess.py?line=508'>509</a>\u001b[0m         process\u001b[39m.\u001b[39mkill()\n",
            "File \u001b[0;32m/usr/lib/python3.9/subprocess.py:1121\u001b[0m, in \u001b[0;36mPopen.communicate\u001b[0;34m(self, input, timeout)\u001b[0m\n\u001b[1;32m   <a href='file:///usr/lib/python3.9/subprocess.py?line=1118'>1119</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_stdin_write(\u001b[39minput\u001b[39m)\n\u001b[1;32m   <a href='file:///usr/lib/python3.9/subprocess.py?line=1119'>1120</a>\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstdout:\n\u001b[0;32m-> <a href='file:///usr/lib/python3.9/subprocess.py?line=1120'>1121</a>\u001b[0m     stdout \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mstdout\u001b[39m.\u001b[39;49mread()\n\u001b[1;32m   <a href='file:///usr/lib/python3.9/subprocess.py?line=1121'>1122</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstdout\u001b[39m.\u001b[39mclose()\n\u001b[1;32m   <a href='file:///usr/lib/python3.9/subprocess.py?line=1122'>1123</a>\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstderr:\n",
            "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
          ]
        }
      ],
      "source": [
        "\n",
        "from utils import pipe, ring, connection, mount_to_bottom, tended_obj, cutout, hollow_screw\n",
        "from solid import cylinder, translate, rotate, cube, hull\n",
        "from solid.utils import *\n",
        "from viewscad import Renderer\n",
        "from math import sqrt\n",
        "r = Renderer()\n",
        "r.width = 700\n",
        "r.height = 700\n",
        "\n",
        "render = r.render\n",
        "\n",
        "\n",
        "def tower_module_thread_adapter(w_socket=1, w_adapter=2, d=160, socket_h=20, tooth=4, gap=0.2):\n",
        "    outer_r = d/2\n",
        "    inner_r = d/2 - w_adapter - tooth - gap\n",
        "    inner_thread_r = d/2 - w_adapter - gap\n",
        "    transition_h = outer_r - inner_r\n",
        "    wall=min(w_adapter, w_socket)\n",
        "\n",
        "    socket = hollow_screw(\n",
        "        radius=outer_r,\n",
        "        wall=wall,\n",
        "        screw_height=socket_h,\n",
        "        tooth_depth=tooth,\n",
        "        tooth_height=2*tooth,\n",
        "        external=False\n",
        "    )\n",
        "\n",
        "    adapter = hollow_screw(\n",
        "        radius=inner_thread_r,\n",
        "        wall=wall,\n",
        "        screw_height=socket_h,\n",
        "        tooth_depth=tooth,\n",
        "        tooth_height=2*tooth,\n",
        "        external=True\n",
        "    )\n",
        "\n",
        "    transition = ring(r1=inner_r, r2=outer_r, w=wall, h=transition_h)\n",
        "\n",
        "    pipe = adapter\n",
        "    pipe += up(socket_h)(transition)\n",
        "    pipe += up(socket_h + transition_h)(socket)\n",
        "\n",
        "    return pipe\n",
        "\n",
        "\n",
        "render(tower_module_thread_adapter(), outfile='./outfiles/tower_module_size_transition.stl')\n"
      ]
    }
  ],
  "metadata": {
    "interpreter": {
      "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
    },
    "kernelspec": {
      "display_name": "Python 3.9.2 64-bit",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.2"
    },
    "orig_nbformat": 4,
    "vscode": {
      "interpreter": {
        "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 2
}
